<?php
/**
  * Copyright (C) 2025 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_views_filter_dates (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

use Drupal\search_api\Query\Query;
use Drupal\search_api\Query\Condition;
use Drupal\search_api\Query\ConditionGroup;

/**
 * Implements hook_search_api_query_alter().
 *
 */
function dge_views_filter_dates_search_api_query_alter(Query $query) {
  $condition_group = $query->getConditionGroup();
  dge_views_filter_dates_alter_conditions($condition_group);
}

function dge_views_filter_dates_alter_conditions(ConditionGroup $group) {
  foreach ($group->getConditions() as $condition) {
   
    if ($condition instanceof ConditionGroup) {
        dge_views_filter_dates_alter_conditions($condition);
    }
    elseif (is_array($condition)) {
      foreach ($condition as $sub_condition) {
        dge_views_filter_dates_process_condition($sub_condition);
      }
    }
    else {
        dge_views_filter_dates_process_condition($condition);
    }
  }
}

function dge_views_filter_dates_process_condition($condition) {
  if ($condition instanceof Condition) {
    $field = $condition->getField();
    $operator = $condition->getOperator();
    $value = $condition->getValue();

    if ($operator === '<=' && !empty($value) && is_numeric($value)) {
      $adjusted_value = $value + 86400; 
      $condition->setValue($adjusted_value);
    }
  }
}