<?php
/**
  * Copyright (C) 2025 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_tfa (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/


use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;
use Drupal\Core\Database\Database;

/**
 * Implementa hook_entity_insert().
 */
function dge_tfa_entity_insert(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof User) {
    $uid = $entity->id();

    if (!$entity->hasRole('administrator')) {
      $user_data = \Drupal::service('user.data');
      $user_tfa_data = $user_data->get('tfa', $uid, 'tfa_email_otp') ?? [];

      $user_tfa_data['enable'] = 1;
      $user_data->set('tfa', $uid, 'tfa_email_otp', $user_tfa_data);
      $user_settings = [
          'saved' => \Drupal::time()->getRequestTime(),
          'status' => true,
          'data' => [
            'plugins' => [
              'tfa_email_otp' => 'tfa_email_otp'
            ],
          ],
          'validation_skipped' => 1,
      ];
      $user_data->set('tfa', $uid, 'tfa_user_settings', $user_settings);
    }
  }
}


