<?php
/**
  * Copyright (C) 2026 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_tfa (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

use Drupal\node\NodeInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Database\Database;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\tfa\TfaLoginTrait;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;

const DGE_TFA_MAX_TIME_RESOLUTION = 300;

/**
 * Implementa hook_entity_insert().
 */
function dge_tfa_entity_insert(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof User) {
    $uid = $entity->id();

    if (!$entity->hasRole('administrator')) {
      $user_data = \Drupal::service('user.data');
      $user_tfa_data = $user_data->get('tfa', $uid, 'tfa_email_otp') ?? [];

      $user_tfa_data['enable'] = 1;
      $user_data->set('tfa', $uid, 'tfa_email_otp', $user_tfa_data);
      $user_settings = [
          'saved' => \Drupal::time()->getRequestTime(),
          'status' => true,
          'data' => [
            'plugins' => [
              'tfa_email_otp' => 'tfa_email_otp'
            ],
          ],
          'validation_skipped' => 1,
      ];
      $user_data->set('tfa', $uid, 'tfa_user_settings', $user_settings);
    }
  }
}

/**
 * Implements hook_form_alter ().
 */
function dge_tfa_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id === 'tfa_entry_form') {
    $access = AccessResult::allowed();
    $access->addCacheContexts(['route']);
    $route = \Drupal::routeMatch();
    $uid = (int) $route->getParameter('uid');
    $temp_store = \Drupal::service('tempstore.private')->get('tfa');
    $uid_check = $temp_store->get('tfa-entry-uid');
    if (is_numeric($uid_check) && ($uid == (int) $uid_check)) {
      
      $metadata = $temp_store->getMetadata('tfa-entry-uid');
      $updated = is_null($metadata) ? 0 : $metadata->getUpdated();
      $final = $updated + DGE_TFA_MAX_TIME_RESOLUTION - time();
      
      $form['tfa_pending_time'] = [
        '#type' => 'hidden',
        '#value' => $final,
      ];

      // Se carga el JS encargado de redirigir al login
      $form['#attached']['library'][] = 'dge_tfa/tfa_timer';
    }
  }

}
