<?php
/**
  * Copyright (C) 2025 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_email_footer_header (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

function sendmail_preprocess_mimemail_message(&$variables) {
    $dgeConfig = \Drupal::config('dge_email_footer_header.config');

    $footer_text = $dgeConfig->get('footer');

    $site_config = \Drupal::configFactory()-> getEditable('system.site');

    $token_service = \Drupal::service('token');
    $replacements = array(
      'site' => $site_config
    );
    $options = array(
      'clear' => TRUE,
    );

    $footer_text_processed = $token_service->replace($footer_text, $replacements, $options);

    $variables['header'] = [
        '#type' => 'processed_text',
        '#text' => $dgeConfig->get('header'),
        '#format' => $dgeConfig->get('header_format')
    ];
    $variables['footer'] = [
        '#type' => 'processed_text',
        '#text' =>  $footer_text_processed,
        '#format' =>  $dgeConfig->get('footer_format')
    ];
}

function sendmail_preprocess_image(&$variables) {
    if (isset($variables['uri'])) {
      $file_url_generator = \Drupal::service('file_url_generator');
      $variables['attributes']['src'] = $file_url_generator->generateAbsoluteString($variables['uri']);
    }
}
