<?php

/**
  * Copyright (C) 2026 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_custom_ckeditor_defaults (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_editor_js_settings_alter().
 */
function dge_custom_ckeditor_defaults_editor_js_settings_alter(array &$settings, $editor = NULL) {

  if (empty($settings['editor']['formats'])) {
    return;
  }

  foreach ($settings['editor']['formats'] as $format_id => &$format) {

    if (empty($format['editorSettings']['config'])) {
      continue;
    }

    $format['editorSettings']['config']['table']['tableProperties']['defaultProperties']['borderStyle'] = 'none';

    $format['editorSettings']['config']['table']['tableCellProperties']['defaultProperties']['borderStyle'] = 'none';
  }
}

