<?php
/**
  * Copyright (C) 2025 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_reset_password_ldap (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Utility\Token;


/**
 * Implements hook_form_FORM_ID_alter()
 */
function dge_reset_password_ldap_form_user_admin_settings_alter(&$form, FormStateInterface $form_state) {

 $mail_config = \Drupal::getContainer()->get('config.factory')->getEditable('dge_reset_password_ldap.email');
 $email_token_help = t('The list of available tokens that can be used in e-mails is provided below.');

 $form['dge_reset_password_ldap_email'] = [
   '#type' => 'details',
   '#title' => t('Email reset password LDAP'),
   '#description' => t('The email that is sent to LDAP users when resetting passwords.') . ' ' . $email_token_help,
   '#group' => 'email',
 ];
 $form['dge_reset_password_ldap_email']['dge_reset_password_ldap_email_subject'] = [
   '#type' => 'textfield',
   '#title' => t('Subject'),
   '#default_value' => $mail_config->get('dge_reset_password_ldap_email.subject'),
   '#maxlength' => 180,
 ];
 $form['dge_reset_password_ldap_email']['dge_reset_password_ldap_email_body'] = [
   '#type' => 'textarea',
   '#title' => t('Body'),
   '#default_value' => $mail_config->get('dge_reset_password_ldap_email.body'),
   '#rows' => 8,
 ];

 $form['#submit'][] = '_reset_password_ldap_email_settings_submit';
}


function _reset_password_ldap_email_settings_submit(array $form, FormStateInterface $form_state) {

  $mail_config = \Drupal::getContainer()->get('config.factory')->getEditable('dge_reset_password_ldap.email');
  $mail_config
    ->set('dge_reset_password_ldap_email.subject', $form_state->getValue('dge_reset_password_ldap_email_subject'))
    ->set('dge_reset_password_ldap_email.body', $form_state->getValue('dge_reset_password_ldap_email_body'))
  ->save();

  $form_state->unsetValue('dge_reset_password_ldap_email.subject');
  $form_state->unsetValue('dge_reset_password_ldap_email.body');
}

/**
 * Implements hook_mail_alter()
 */
function dge_reset_password_ldap_mail_alter(&$message) {
  if ($message['id'] == 'user_password_reset') {
    $account = $message['params']['account'];
    
    $roles = user_roles($account);
    $authmap = \Drupal::service('externalauth.authmap');
    $authname = $authmap->get((int) $account->id(), 'ldap_user');

    if ($authname || in_array('ldap', $roles)) {
      $message['id'] = 'user_ldap_password_reset';
      $mail_config = \Drupal::getContainer()->get('config.factory')->getEditable('dge_reset_password_ldap.email');
      
      $body =  $mail_config->get('dge_reset_password_ldap_email.body');

      $token_service = \Drupal::service('token');
      $replacements = array(
        'user' => $account,
      );
      $options = array(
        'clear' => TRUE,
      );
      
      $subject = $mail_config->get('dge_reset_password_ldap_email.subject');
      $subject = $token_service->replace($subject, $replacements, $options);
      $message['subject'] = $subject;

      $body = $token_service->replace($body, $replacements, $options);
      $message['body'] = array();
      $message['body'][] = $body;
    }
  }
}