<?php
/**
  * Copyright (C) 2025 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_unique_role_name (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for the role form.
 */
function dge_unique_role_name_form_user_role_form_alter(array &$form, FormStateInterface $form_state)
{
  $form['#validate'][] = 'dge_unique_role_name_validate_role_label';
}

function dge_unique_role_name_validate_role_label(array &$form, FormStateInterface $form_state)
{
  $label = $form_state->getValue('label');
  $rid = $form_state->getValue('rid');

  if (!empty($label)) {
    $existing_roles = \Drupal::entityQuery('user_role')
      ->condition('label', $label)
      ->condition('id', $rid, '<>')
      ->execute();

    if (!empty($existing_roles)) {
      $form_state->setErrorByName('label', t('The role label is already in use.'));
    }
  }
}
