<?php
/**
  * Copyright (C) 2025 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_password_simple_form (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dge_password_simple_form_form_user_form_alter(&$form, FormStateInterface $form_state)
{
  if (isPassResetForm()) {
    $fields_to_hide = [
      'field_nombre', 'field_apellidos', 'field_telefono', 'field_posicion', 'field_otra_organizacion',
      'field_nombre_de_la_otra_organiza', 'field_comentarios_adicionales', 'field_organizacion', 'field_ckan_user_id',
      'field_ckan_user_name'
    ];

    $form['contact']['#access'] = false;
    $form['language']['#access'] = false;

    foreach ($fields_to_hide as $field_name) {
      $form[$field_name]['#access'] = false;
      $form[$field_name][STATES] = ['visible' => ['value' => false]];
    }

    if (empty($_SESSION)) {
      $_SESSION = ['dge_password_simple_form' => TRUE];
    }
  }
}

function
dge_password_simple_form_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability)
{
  if (isPassResetForm()) {
    unset($data['tabs'][0]['entity.user.canonical']);
  }
}


function isPassResetForm()
{
  $request_stack = \Drupal::service('request_stack');
  $current_request = $request_stack->getCurrentRequest();
  $request_uri = $current_request->getRequestUri();
  
  return strpos($request_uri, 'pass-reset-token') !== false;
}
/**
 * Implements hook_module_implements_alter().
 *
 */
function dge_password_simple_form_module_implements_alter(&$implementations, $hook)
{
  if ($hook == 'form_alter' && isset($implementations['dge_password_simple_form'])) {
    $group = $implementations['dge_password_simple_form'];
    unset($implementations['dge_password_simple_form']);
    $implementations['dge_password_simple_form'] = $group;
  }
}
