<?php
/**
  * Copyright (C) 2025 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_sendinblue (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * Implements hook_mail().
 */
function dge_sendinblue_mail($key, &$message, $params) {
    switch ($key) {
        case 'unsubscribe':
        $headers['headers'] = $params['headers'];
        $message['from'] = \Drupal::config('system.site')->get('mail');
        $message['subject'] = $params['subject'];
        $message['body'][] = $params['body'];
        break;
    }
}

/**
 * Implements hook_schema_translation().
 */
function dge_sendinblue_schema_translation() {
  $schema['dge_sendinblue']['dge_sendinblue_unsuscribe_email_subject'] = ['dge_sendinblue_unsuscribe_email_subject'];
  $schema['dge_sendinblue']['dge_sendinblue_unsuscribe_email_content'] = ['dge_sendinblue_unsuscribe_email_content'];
  return $schema;
}